### ISSUE TITLE
ES6 Function Component Syntax Flag

### ISSUE THREAD

**Issue by waynevanson** [grabantot/react-cli#1]
Hi There,

Great to see how flexible you'd like this CLI to be. 

On the note of flexibility, I think a feature to use ES6 function components should be added, as the presumption is `function MyComponentName() { ... }`
``` typescript
const MyComponentName = ()  => {
    return <div></div>
}
```
that way, in a config file we can do the following:
``` json
{
  "function-component-es6syntax": "true"
}
```
Not sure what it's officially called, but you get the jist. We can figure out the name later.

Once I start using this a bit more and figure out how it's built, I shall contribute.

**Comment by anatol-grabowski** [comment]
Hi,

My thinking behind why this was not added:
1. We already have a `-f` flag to create a functional component: `react-cli -f FuncCmp`.
2. We provide a way to customize the code of each template: `mkdir cfgdir && react-cli config cfgdir && vim cfgdir/FunctionalComponent.js`.
3. A user will likely want to be consistent and make all of his functional components to be either functions or arrow functions.
4. Since mixing of regular and arrow functions is not needed I tried to keep it simple.

Other thoughts:
Sometimes you have to convert a functional component to a class component or vice versa. I prefer regular functions so I've implemented this conversion functionality only for regular functions. If we are going to introduce this functionality for conversion to arrow functions then we are going to need a flag indicating whether it should be a regular or arrow function. This flag can be added to a config (static) or as the cli option. A cli option is more flexible - I suggest we call it `-a --arrow`. If we add this functionality for conversion then we may add a template (`ArrowFunctionalComponent.js`) for creation as well (to be consistent with `-f` flag functionality).

So I'm open to the idea but I think `-a --arrow` + `templates/ArrowFunctionalComponent.js` approach is better than `"function-component-es6syntax"` in the config. Anyway I don't think I'm going to work on it anytime soon but you are welcome to create a PR ;)

What I think would be cool is a feature when user can create custom templates or even modules that modify the source code by custom rules and assign custom cli flags for them in the config.

**Comment by waynevanson** [comment]
> I prefer regular functions so I've implemented this conversion functionality only for regular functions.

I believe that it's a matter of preference with using fat arrows and functions. I've found using fat arrows on components and functions on actual functions creates a nice distinction, as `constants` are stateful and act like a component - a physical representation of HTML, CSS and JS.

> So I'm open to the idea but I think -a --arrow + templates/ArrowFunctionalComponent.js approach is better than "function-component-es6syntax" in the config. 

I think having config properties that describe what it does is ideal. `function-component-es6syntax` is too long, but maybe something like the below:

``` typescript
{
  "componentType" : "[class | functional | pure]",
  "componentFunctionStyle": "[const | function]",
  "compontentFunctions": "[const | function]"
}
```

Either way, I'm very excited to be here. I will work on Typescript then address this.
